-- Phase 2: items, donations (pledges), their lines, and editable site settings.
-- Runs inside the schema set by PGSCHEMA via search_path — no schema prefix
-- after the schema itself is created below.

-- Initial migration also bootstraps the app schema and the table
-- scripts/migrate.js uses to record applied migrations.
CREATE SCHEMA IF NOT EXISTS church_donations;

CREATE TABLE schema_migrations (
  filename TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE items (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 100),
  unit_price_crc INTEGER NOT NULL CHECK (unit_price_crc > 0),
  goal_quantity INTEGER CHECK (goal_quantity IS NULL OR goal_quantity > 0),  -- NULL = no goal / no countdown
  active BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE donations (
  id SERIAL PRIMARY KEY,
  client_token UUID NOT NULL UNIQUE,   -- generated by the browser per form; makes double-submit idempotent (Phase 4)
  donor_name TEXT NOT NULL CHECK (length(btrim(donor_name)) BETWEEN 1 AND 100),
  donor_phone TEXT NOT NULL CHECK (donor_phone ~ '^[0-9]{8}$'),
  total_crc INTEGER NOT NULL CHECK (total_crc > 0),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','received','cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status_changed_at TIMESTAMPTZ
);
CREATE INDEX idx_donations_status_created ON donations (status, created_at DESC);

CREATE TABLE donation_items (
  id SERIAL PRIMARY KEY,
  donation_id INTEGER NOT NULL REFERENCES donations(id) ON DELETE CASCADE,
  item_id INTEGER NOT NULL REFERENCES items(id),          -- no cascade: items are deactivated, never deleted
  quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 9999),
  unit_price_crc INTEGER NOT NULL CHECK (unit_price_crc > 0),  -- copied from items at pledge time
  UNIQUE (donation_id, item_id)
);
CREATE INDEX idx_donation_items_item ON donation_items (item_id);

CREATE TABLE site_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO site_settings (key, value) VALUES
  ('welcome_message', 'Bienvenido. "Cada uno dé como propuso en su corazón, no con tristeza ni por necesidad, porque Dios ama al dador alegre." — 2 Corintios 9:7'),
  ('payment_instructions', '¡Gracias por tu compromiso! Puedes entregar tu aporte en efectivo a un hermano de la iglesia o por SINPE Móvil.'),
  ('sinpe_number', '');
